"set guifont=DejaVu\ Sans\ Mono:h15  " Font family and font size.
set guifont=Source\ Code\ Pro:h15   " Font family and font size.
set antialias                       " MacVim: smooth fonts.
set encoding=utf-8                  " Use UTF-8 everywhere.
set guioptions-=T                   " Hide toolbar.
set lines=27 columns=92             " Window dimensions.


set guioptions-=r                   " Don't show right scrollbar
set guioptions-=L

set shell=zsh\ -i                   " Use zsh env vars

autocmd VimResized * wincmd =       " Automatically resize windows
