"set guifont=DejaVu\ Sans\ Mono:h15  " Font family and font size.
"set guifont=Source\ Code\ Pro\ For\ Powerline:h11   " Font family and font size.
set guifont=Menlo\ For\ Powerline:h13   " Font family and font size.
set antialias                       " MacVim: smooth fonts.
set encoding=utf-8                  " Use UTF-8 everywhere.
set guioptions-=T                   " Hide toolbar.
set guioptions-=r
set guioptions-=L                   " hide scrollbars
set lines=40 columns=125            " Window dimensions.

set shell=zsh\ -i                   " Use zsh env vars

autocmd VimResized * wincmd =       " Automatically resize windows

nnoremap <M-DOWN> 4j
nnoremap <M-UP> 4k

" do not go to end of file
nnoremap <S-CR> <CR>
